CREATE TABLE CAB_REF (
  IDONLINE VARCHAR(30) CHARACTER SET NONE DEFAULT '' NOT NULL COLLATE NONE,
  NROAUDITORIA VARCHAR(10) CHARACTER SET NONE DEFAULT '' COLLATE NONE,
  EFECTOR VARCHAR(6) CHARACTER SET NONE COLLATE NONE,
  FECHA VARCHAR(8) CHARACTER SET NONE COLLATE NONE,
  CODOS VARCHAR(6) CHARACTER SET NONE COLLATE NONE,
  IDZONA VARCHAR(2) CHARACTER SET NONE COLLATE NONE,
  NRODOC VARCHAR(15) CHARACTER SET NONE COLLATE NONE,
  IDPROF VARCHAR(6) CHARACTER SET NONE COLLATE NONE,
  FEPEDIDO VARCHAR(8) CHARACTER SET NONE COLLATE NONE,
  IDDIAG VARCHAR(6) CHARACTER SET NONE COLLATE NONE,
  DIFERIDA VARCHAR(1) CHARACTER SET NONE COLLATE NONE,
  OBSERVACION VARCHAR(256) CHARACTER SET NONE COLLATE NONE,
  ALTAPAC VARCHAR(1) CHARACTER SET NONE COLLATE NONE,
  AUDITADA VARCHAR(1) CHARACTER SET NONE COLLATE NONE,
  TRANSFERIDA VARCHAR(1) CHARACTER SET NONE COLLATE NONE,
  OBSAUDITOR VARCHAR(256) CHARACTER SET NONE COLLATE NONE,
  ANULADA VARCHAR(1) CHARACTER SET NONE COLLATE NONE);


ALTER TABLE CAB_REF ADD CONSTRAINT PK_CAB_REF PRIMARY KEY (IDONLINE);


CREATE INDEX CAB_REF_FECHA ON CAB_REF(FECHA);

CREATE INDEX CAB_REF_PROF ON CAB_REF(EFECTOR,FECHA);