//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testws.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="SDT_CobAdici2", Namespace="IAPOS_WS", ItemName="SDT_CobAdici2.SDT_CobAdic_Item")]
    [System.SerializableAttribute()]
    public class SDT_CobAdici2 : System.Collections.Generic.List<testws.ServiceReference.SDT_CobAdici2.SDT_CobAdic_Item> {
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="SDT_CobAdici2.SDT_CobAdic_Item", Namespace="IAPOS_WS")]
        [System.SerializableAttribute()]
        public partial class SDT_CobAdic_Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
            
            [System.NonSerializedAttribute()]
            private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
            
            private sbyte GravCodGra_Codigo_GravamenField;
            
            private string GravDesGra_Descrip_GravamenField;
            
            public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
                get {
                    return this.extensionDataField;
                }
                set {
                    this.extensionDataField = value;
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
            public sbyte GravCodGra_Codigo_Gravamen {
                get {
                    return this.GravCodGra_Codigo_GravamenField;
                }
                set {
                    if ((this.GravCodGra_Codigo_GravamenField.Equals(value) != true)) {
                        this.GravCodGra_Codigo_GravamenField = value;
                        this.RaisePropertyChanged("GravCodGra_Codigo_Gravamen");
                    }
                }
            }
            
            [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
            public string GravDesGra_Descrip_Gravamen {
                get {
                    return this.GravDesGra_Descrip_GravamenField;
                }
                set {
                    if ((object.ReferenceEquals(this.GravDesGra_Descrip_GravamenField, value) != true)) {
                        this.GravDesGra_Descrip_GravamenField = value;
                        this.RaisePropertyChanged("GravDesGra_Descrip_Gravamen");
                    }
                }
            }
            
            public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
            
            protected void RaisePropertyChanged(string propertyName) {
                System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
                if ((propertyChanged != null)) {
                    propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="IAPOS_WS", ConfigurationName="ServiceReference.BEWsValidaAfiSoapPort")]
    public interface BEWsValidaAfiSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (BEWsValidaAfi.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="IAPOS_WSaction/ABEWSVALIDAAFI.Execute", ReplyAction="*")]
        testws.ServiceReference.ExecuteResponse Execute(testws.ServiceReference.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BEWsValidaAfi.Execute", WrapperNamespace="IAPOS_WS", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=0)]
        public string Usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=1)]
        public string Passwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=2)]
        public string Nafiliado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=3)]
        public string Badocnumdo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=4)]
        public string Tidocodigo_de_documento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=5)]
        public long Ogorcodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=6)]
        public string Fechpresta;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Usuario, string Passwd, string Nafiliado, string Badocnumdo, string Tidocodigo_de_documento, long Ogorcodigo, string Fechpresta) {
            this.Usuario = Usuario;
            this.Passwd = Passwd;
            this.Nafiliado = Nafiliado;
            this.Badocnumdo = Badocnumdo;
            this.Tidocodigo_de_documento = Tidocodigo_de_documento;
            this.Ogorcodigo = Ogorcodigo;
            this.Fechpresta = Fechpresta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="BEWsValidaAfi.ExecuteResponse", WrapperNamespace="IAPOS_WS", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=0)]
        public string Nafiliado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=1)]
        public string Badocnumdo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=2)]
        public string Tidocodigo_de_documento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=3)]
        public string Estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=4)]
        public short Edad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=5)]
        public string Fechanac;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=6)]
        public string Sexo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=7)]
        public string Codpos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=8)]
        public string Localidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=9)]
        public string Departamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=10)]
        public string Apenom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=11)]
        public string Nafititu;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=12)]
        public int Bapernroin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=13)]
        public int Plan;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=14)]
        public string Servicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=15)]
        public testws.ServiceReference.SDT_CobAdici2 Sdt_cob;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=16)]
        public string Recupero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=17)]
        public string Msgcod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=18)]
        public string Msgdsc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=19)]
        public int Beinsticodigo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=20)]
        public string Beinstidescripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=21)]
        public string Tidodescri_documento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=22)]
        public int Batitnroin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=23)]
        public string Batitdeshaberes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="IAPOS_WS", Order=24)]
        public string Batithabilitado;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(
                    string Nafiliado, 
                    string Badocnumdo, 
                    string Tidocodigo_de_documento, 
                    string Estado, 
                    short Edad, 
                    string Fechanac, 
                    string Sexo, 
                    string Codpos, 
                    string Localidad, 
                    string Departamento, 
                    string Apenom, 
                    string Nafititu, 
                    int Bapernroin, 
                    int Plan, 
                    string Servicio, 
                    testws.ServiceReference.SDT_CobAdici2 Sdt_cob, 
                    string Recupero, 
                    string Msgcod, 
                    string Msgdsc, 
                    int Beinsticodigo, 
                    string Beinstidescripcion, 
                    string Tidodescri_documento, 
                    int Batitnroin, 
                    string Batitdeshaberes, 
                    string Batithabilitado) {
            this.Nafiliado = Nafiliado;
            this.Badocnumdo = Badocnumdo;
            this.Tidocodigo_de_documento = Tidocodigo_de_documento;
            this.Estado = Estado;
            this.Edad = Edad;
            this.Fechanac = Fechanac;
            this.Sexo = Sexo;
            this.Codpos = Codpos;
            this.Localidad = Localidad;
            this.Departamento = Departamento;
            this.Apenom = Apenom;
            this.Nafititu = Nafititu;
            this.Bapernroin = Bapernroin;
            this.Plan = Plan;
            this.Servicio = Servicio;
            this.Sdt_cob = Sdt_cob;
            this.Recupero = Recupero;
            this.Msgcod = Msgcod;
            this.Msgdsc = Msgdsc;
            this.Beinsticodigo = Beinsticodigo;
            this.Beinstidescripcion = Beinstidescripcion;
            this.Tidodescri_documento = Tidodescri_documento;
            this.Batitnroin = Batitnroin;
            this.Batitdeshaberes = Batitdeshaberes;
            this.Batithabilitado = Batithabilitado;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BEWsValidaAfiSoapPortChannel : testws.ServiceReference.BEWsValidaAfiSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BEWsValidaAfiSoapPortClient : System.ServiceModel.ClientBase<testws.ServiceReference.BEWsValidaAfiSoapPort>, testws.ServiceReference.BEWsValidaAfiSoapPort {
        
        public BEWsValidaAfiSoapPortClient() {
        }
        
        public BEWsValidaAfiSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BEWsValidaAfiSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BEWsValidaAfiSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BEWsValidaAfiSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        testws.ServiceReference.ExecuteResponse testws.ServiceReference.BEWsValidaAfiSoapPort.Execute(testws.ServiceReference.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(
                    string Usuario, 
                    string Passwd, 
                    ref string Nafiliado, 
                    ref string Badocnumdo, 
                    ref string Tidocodigo_de_documento, 
                    long Ogorcodigo, 
                    string Fechpresta, 
                    out short Edad, 
                    out string Fechanac, 
                    out string Sexo, 
                    out string Codpos, 
                    out string Localidad, 
                    out string Departamento, 
                    out string Apenom, 
                    out string Nafititu, 
                    out int Bapernroin, 
                    out int Plan, 
                    out string Servicio, 
                    out testws.ServiceReference.SDT_CobAdici2 Sdt_cob, 
                    out string Recupero, 
                    out string Msgcod, 
                    out string Msgdsc, 
                    out int Beinsticodigo, 
                    out string Beinstidescripcion, 
                    out string Tidodescri_documento, 
                    out int Batitnroin, 
                    out string Batitdeshaberes, 
                    out string Batithabilitado) {
            testws.ServiceReference.ExecuteRequest inValue = new testws.ServiceReference.ExecuteRequest();
            inValue.Usuario = Usuario;
            inValue.Passwd = Passwd;
            inValue.Nafiliado = Nafiliado;
            inValue.Badocnumdo = Badocnumdo;
            inValue.Tidocodigo_de_documento = Tidocodigo_de_documento;
            inValue.Ogorcodigo = Ogorcodigo;
            inValue.Fechpresta = Fechpresta;
            testws.ServiceReference.ExecuteResponse retVal = ((testws.ServiceReference.BEWsValidaAfiSoapPort)(this)).Execute(inValue);
            Nafiliado = retVal.Nafiliado;
            Badocnumdo = retVal.Badocnumdo;
            Tidocodigo_de_documento = retVal.Tidocodigo_de_documento;
            Edad = retVal.Edad;
            Fechanac = retVal.Fechanac;
            Sexo = retVal.Sexo;
            Codpos = retVal.Codpos;
            Localidad = retVal.Localidad;
            Departamento = retVal.Departamento;
            Apenom = retVal.Apenom;
            Nafititu = retVal.Nafititu;
            Bapernroin = retVal.Bapernroin;
            Plan = retVal.Plan;
            Servicio = retVal.Servicio;
            Sdt_cob = retVal.Sdt_cob;
            Recupero = retVal.Recupero;
            Msgcod = retVal.Msgcod;
            Msgdsc = retVal.Msgdsc;
            Beinsticodigo = retVal.Beinsticodigo;
            Beinstidescripcion = retVal.Beinstidescripcion;
            Tidodescri_documento = retVal.Tidodescri_documento;
            Batitnroin = retVal.Batitnroin;
            Batitdeshaberes = retVal.Batitdeshaberes;
            Batithabilitado = retVal.Batithabilitado;
            return retVal.Estado;
        }
    }
}
